# Generated by Django 5.1.2 on 2024-11-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0003_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
