# Generated by Django 5.1.2 on 2024-11-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0004_alter_users_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
