# Generated by Django 5.1.2 on 2024-11-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0005_rename_firstname_users_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='kys_details',
            new_name='kyc_details',
        ),
    ]
