# Generated by Django 5.1.2 on 2024-11-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0008_alter_users_table_alter_wallets_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
