# Generated by Django 5.1.2 on 2024-11-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0009_alter_wallets_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
