# Generated by Django 5.1.2 on 2024-11-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0012_alter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='user_id',
        ),
        migrations.AddField(
            model_name='wallets',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='exchange_app.users'),
        ),
    ]
